ngine-io/cs

- cs.py
This patch omits parameters if values are empty string.
Now cs doesn't generate correct signature when empty strings are passed.
This causes  ansible's  cloudstack inventory script errors when project id is not specified.
> Omit empty string parameters

- cs.py
Dealing with users about a wrong configured endpoint url is annoying. :) Users get a ValueError for a non json response. I tried to make it more user friendly if endpoint is wrong configured.
~~~
python cs.py listVirtualMachines
Cloudstack error:
"No JSON object could be decoded. Make sure endpoint URL 'https://ma-cloud.swisstxt.ch/client/apis' is correct."%
~~~
> handle non json response more user friendly

- cs.py
This patch changes how to wait an async job.
It waits for the job until `jobstatus != 0` because `jobprocstatus` can be 0 even if the job is still processing.
cs can't get jobresult if the job takes more than 3 seconds. 
```sh
$ cs deployVirtualMachine zoneid=baf86a6e-4e3b-428e-8fd0-7fda43e468d4 serviceofferingid=e01a9f32-55c4-4c0d-9b7c-d49a3ccfd3f6 templateid=ec45fa26-e5d0-45a7-b57d-0c3f8e36ff3b
Polling result... ^C to abort
{
"accountid": "6c9ce4be-ed0b-477b-aa76-f0cb1b7a200b", 
"cmd": "org.apache.cloudstack.api.command.user.vm.DeployVMCmd", 
"created": "2015-11-25T09:14:08+0900", 
"jobid": "609d8aed-95e5-4393-979b-a7f954ef0682", 
"jobinstanceid": "f09c9845-99d2-44d4-85c2-857b01307df2", 
"jobinstancetype": "VirtualMachine", 
"jobprocstatus": 0, 
"jobresultcode": 0, 
"jobstatus": 0, …
```
> wait async job until jobstatus != 0 

- cs.py
Not sure if it has ever worked before but it should.
> fix CLOUDSTACK_REGION ignored if used as lib

- cs.py
And don't display a message saying this is an error. IMO, it makes
easier to use cs inside scripts.
> When CloudStack returns an error, use 1 as return code

- cs.py
Fix 2 small things for the output:
- ~~stdout instead of stderr for the waiting message~~
- append a `\n` after the result output to not have the last `} ` on the same line as the prompt
> Fix output

- cs/__init__.py
I was trying to `jq` the error output, but got bitten by the fact that the JSON output was displayed on `stderr`. Then activating the `quiet` revealed the pink mast.
**Before**
```
$ cs -q listAsyncJobs startdate="2018-01-08T08:10:00+0100" 
Traceback (most recent call last):
File "/home/yoan/exoscale/cs/venv/bin/cs", line 11, in <module>
load_entry_point('cs', 'console_scripts', 'cs')()
File "/home/yoan/exoscale/cs/cs/__init__.py", line 118, in main
sys.stdout.write(_format_json(response))
File "/home/yoan/exoscale/cs/cs/__init__.py", line 37, in _format_json
output = json.dumps(data, indent=2, sort_keys=True)
File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
**kw).encode(obj)
File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
chunks = list(chunks)
File …
```
> fix: quiet mode

- cs/client.py
- tests.py
scaleVirtualMachine requires to send key/value for the details... this wasn't supported.
https://cloudstack.apache.org/api/apidocs-4.7/user/scaleVirtualMachine.html
Also fixes the signature for non-string values, e.g. int
> client: support sending dict

- cs/client.py
- tests.py
CloudStack requires userdata to be byte-encoded. This patch allows to pass byte-encoded userdata.
> Allow byte-encoded userdata

- cs/client.py
- tests.py
because I'm doing crazy things in _egoscale_, I'd love to be able to have extra keys into a region.
https://github.com/exoscale/egoscale/tree/less-types/cmd/cs#configuration
> cli: allow extraneous keys in cloudstack.ini

- cs/__init__.py
- cs/client.py
- tests.py
for busy devOps with too many regions to manage.
```ini
[testing]
theme = native
[prod]
theme = rrt
```
> cli: enable themes per region

- cs/client.py
- tests.py
So I we send specific `Accept-Encoding` and probably other stuff in the future
> client: enable headers in requests

- cs/client.py
Try to unbreak situations where the client goes into an infinite _pagination mode_ when using it with `fetch_list=True`.
```
cs listStorageProviders type=primary page=1
{
"count": 1,
"dataStoreProvider": [
{
"name": "DefaultPrimary",
"type": "PRIMARY"
}
]
}
cs listStorageProviders type=primary page=2
{
"count": 1,
"dataStoreProvider": [
{
"name": "DefaultPrimary",
"type": "PRIMARY"
}
]
}
```
what could go wrong?
also: https://github.com/ansible/ansible/pull/40233
> client: avoid infinite loop on broken pagination

- .travis.yml
- README.rst
https://mobile.twitter.com/codewithanthony/status/1014168756342251521
with `sudo: required` we may have xenial.
> travis: build 3.7 on xenial

- README.rst
- cs/client.py
- setup.py
- tests.py
To deactivate it, set the expiration to a negative value. Otherwise it does a "safe" 10 minutes and let you configure it like the others. A negative value deactivates the v3 version.
http://docs.cloudstack.apache.org/en/4.11.1.0/developersguide/dev.html?enabling-api-call-expiration
New dependency: [`pytz`](https://pypi.org/project/pytz/)
cf. https://github.com/exoscale/egoscale/pull/304
> client: enforce signatureVersion=3

- cs/_async.py
**What I did**
```python
await cs.listVirtualMachines(fetch_list=True)
```
**What happened**
```json
{
"count": 10,
"virtualmachine": [{...}]
}
```
**What was expected**
```json
[{...}]
```
> async: fetch_list=True to return a list

- README.rst
- cs/client.py
- tests.py
Using `CLOUDSTACK_OVERRIDES`, you can mix the `cloudstack.ini` and
the env. As the default behaviour favors the config file over
the environment. The value is a separated list of names such
as the one found in the ini.
Build upon the previous work done by @resmo, #68
> client: allow to mix cloudstack.ini and environ

- README.rst
- cs/__init__.py
- cs/client.py
- tests.py
```console
> cs --trace listZones > /dev/null     
GET https://api.exoscale.com/compute?apiKey=EXOc94bc655ff901b7218a5c3cd&command=listZones&response=json&signatureVersion=3&expires=2018-11-12T13%3A47%3A39%2B0000&signature=<< sig >>
200 OK
Date: Mon, 12 Nov 2018 13:37:19 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 1104
Connection: close
Vary: Accept-Encoding, Accept-Encoding, User-Agent
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-XSS-Protection: 1; mode=block
X-Request-Id: 57c51ef5-bee4-48c1-865e-d39af14f55dd 
<< body >>
```
> client: add trace option

- cs/client.py
When you set up trace=True and try to launch async call with fetch_result, you'll get the following exception in _jobresult() method:
AttributeError: 'str' object has no attribute 'items'
This is caused by overwriting "headers" variable in _request() method when tracing is enabled. 
As a result, headers are passed to _jobresult() as a string. 
The solution is to rename headers variable in self.trace ifblock to something else.
> Fix exception when fetch_results=True and trace=True

- cs/client.py
the configuration refactoring #76 introduced a regression regarding the error raised when the region doesn't exist in the ini file.
```console
% cs -r foo listZones
Traceback (most recent call last):
...
ValueError: endpointthe configuration is missing the following keys: , keythe configuration is missing the following keys: , secret
```
**then**
`[foo] ` doesn't exist in the ini file.
```console
% cs -r foo listZones       
Error: region 'foo' not in config
```
`[foo]` is incomplete in the ini file.
```console
% cs -r foo listZones
Traceback (most recent call last):
....
ValueError: the configuration is missing the following keys: endpoint, key, secret
```
> client: restore error when section is missing

- .gitignore
- setup.cfg
- setup.py
- tox.ini
```
================================= test session starts ==================================
platform linux -- Python 3.7.0rc1, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/yoan/exoscale/cs, inifile: setup.cfg
plugins: cov-2.5.1, flakes-3.0.2, pep8-1.0.6
collected 11 items                                                                     
tests.py ...........                                                             [100%]
--------- coverage: platform linux, python 3.7.0-candidate-1 ---------
Name             Stmts   Miss  Cover   Missing
----------------------------------------------
cs/__init__.py      92     71    23%   10-11, 15-17, 29-30, 38-45, 49-130
cs/__main__.py       3      3     0%   1-5
cs/_async.py        77     67    13%   13-15, 18-20, 24-89, 92-113
cs/client.py …
```
> tests: use pytest and simplify tox file

- README.rst
- cs/client.py
- tests.py
This allows such configuration, which is mostly useful for special developer cases.
```ini
endpoint = https://192.168.1.1/compute
dangerous_no_tls_verify = false
```
http://docs.python-requests.org/en/master/user/advanced/?#ssl-cert-verification
> config: accept verify=False

- tests.py
Python2.6 support was dropped a while ago. via #89
> tests: remove python2.6 specific hack

- cs/__init__.py
- cs/client.py
When the error occurs before reaching CloudStack, the reason is often hidden by the fact that the answer isn't in the expected application/json
**Before**
```python
cs.deployVirtualMachine(userdata="...")
```
> CloudStackException("JSON (application/json) was expected, got 'text/html'")
**After**
```python
cs.deployVirtualMachine(userdata="...")
```
> CloudStackException('HTTP 414 Request-URI Too Large', "Make sure endpoint URL 'https://ppapi.exoscale.ch/compute' is correct.")
> client: refactor exceptions

- cs/client.py
In README we specify that if we do not set job_timeout, we will wait forever.
But we was defaulting to 0 => do not wait at all
> FIX: job_timeout should be None if not specified => wait forever

- tox.ini
@chrisglass' life will be even smoother now
E.g. with the very lousy distro of mine.
```
py27: commands succeeded
py34: commands succeeded
py35: commands succeeded
py36: commands succeeded
py37: commands succeeded
SKIPPED:  py38: InterpreterNotFound: python3.8
lint: commands succeeded
congratulations :)
```
> tox: skip missing interpreters

- cs/__init__.py
silly traceback...
```
cs.client.CloudStackException: ('HTTP 401 response from CloudStack', {'errorcode': 401, 'errortext': 'unable to verify user credentials and/or request signature', 'uuidList': []})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/yoan/.local/bin/cs", line 10, in <module>
sys.exit(main())
File "/home/yoan/.local/lib/python3.7/site-packages/cs/__init__.py", line 111, in main
sys.stderr.write("\n".join(e.args))
TypeError: sequence item 1: expected str instance, dict found
```
**then**
```
CloudStack error: HTTP 401 response from CloudStack
{'errorcode': 401, 'errortext': 'unable to verify user credentials and/or request signature', 'uuidList': []}
```
```json
{
"errorresponse": {
"errorcode": 401, …
```
> cli: fix error on errors

- .gitignore
- cs/client.py
- tests.py
This change adds support for user-defined arbitrary headers to be
injected to every outgoing HTTP request to the Exoscale API.
Configuration is done through a new `header_<NAME>` key in the
`cloudstack.ini` file:
```ini
[cloudstack]
endpoint = https://api.exoscale.ch/compute
key = EXO************************
secret = *******************************************
timeout = 60
header_X-Custom-Header1 = foo
header_X-Custom-Header2 = bar
```
Story: [The cs library should allow adding arbitrary headers](https://app.clubhouse.io/exoscale/story/2542)
> Add support for custom HTTP request headers

- cs/client.py
This makes it easier to add signing hooks.
> client: mutate params as part of the signature process

- cs/client.py
- tox.ini
This change adds a built-in implementation of the `strtobool()` function
from the `distutils.util` module to avoid pulling a dependency on
deprecated module `imp`.
> Add built-in implementation of strtobool

- cs/__init__.py
- cs/_async.py
- cs/client.py
This allows easy access to the underlying API error, whether we're in an
async job context or a synchronous API call.
> exceptions: introduce an exception subclass for API errors

- cs/_async.py
- cs/client.py
This allows passing `fetch_result=True` to a cs client for it to poll
all async jobs by default, instead of having to pass the parameter to
individual API calls.
> introduce client-level fetch_result

- cs/client.py
This change adds support for user-provided Requests HTTP session
attribute, allowing the caller for example to implement a retry policy
for HTTP calls.
> Support user-provided Requests HTTP session

- README.rst
Replace Exoscale compute endpoint `/compute` by `/v1` in README
> Replace Exoscale compute endpoint /compute by /v1

- .travis.yml
- cs/__init__.py
- cs/client.py
- tests.py
While investigating compute-tests failures, we faced poor `HTTP 431 response from CloudStack` exceptions which do not expose the `error` field. This PR makes overrides the `__str__` method so that we expose the error field so we will see it in CI.
Travis is not working anymore, but I run `tox` locally which includes tests and linters, and they work fine. I only had to comment out `27` in the `tox` file as there is one place which ruins Python 2 support.
> Better API Exception rendering

- cs/__init__.py
- cs/client.py
- tests.py
Versions below 3.8 (including Python 2) are not supported, drop related code.
> Drop leftovers from EOL Python version support

- setup.cfg
- tox.ini
`pytest-runner` has been considered deprecated upstream since 2019:
https://github.com/pytest-dev/pytest-runner/commit/78a492cb9f611a4fccaf6556c966b848885833ba
and the repo upstream was archived over a year ago (December 3, 2023).
`pytest-runner` is deprecated in Fedora:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XWRCM4AOKM7KOMR3NLXDD2F7G65ALPKJ/#4BGKLXGODMGMDQKTLLYWD3R4NQ27UAJC
Remove `pytest-runner` and fully migrate to `tox`.
> Remove `pytest-runner`
