.travis.yml
also see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
=> speed up travis by not using sudo

.travis.yml, cs.py, tests.py, tox.ini
I have to use python 2.6 on one host. Would be glad if you can merge it in.
=> fix python 2.6 compatibility

cs.py
hmm this something speak against doing the key handling like little ponies would do?
=> simplify key handling

cs.py
With these changes you can now have different sections in your `.cloudstack.ini`, each one represents a region.
~~~
[exoscale]
endpoint = https://api.exoscale.ch/compute
key = ...
secret = ...
[my-cloud]
endpoint = https://cloud.example.com/client/api
key = ...
secret = ...
~~~
Per cli you can simple add a `--region=exoscale` to use the *region* wanted. default *region* will be `cloudstack`.
Usage in python code is quite simple, just pass the region to the `read_config()`:
~~~
from cs import CloudStack, read_config
cs = CloudStack(**read_config('exoscale'))
~~~
Of course this still works as before:
~~~
from cs import CloudStack, read_config
cs = CloudStack(**read_config())
~~~
This allows me to add region support to Ansible by just adding a single param! 
~~~
def _connect(self):
... …
=> add region support

README.rst, cs.py
Here is a suggestion for adding verify ssl config to cs.
=> Add SSL verification config

.travis.yml, setup.py, tox.ini
The badge will be green again.
=> Using tox-travis.

cs/__init__.py
=> Pretty print the errors as well.

README.rst
=> doc: add some badges pointing to PyPI

README.rst, setup.py
and remove that little `u""`
closes #36
=> Move the async support to the extras

cs/client.py, tests.py
=> client: fix multiple pageSize

README.rst
the badges are still broken... for some reason
=> readme: links to pypi.org

.travis.yml, cs/__init__.py, cs/client.py, setup.py, tox.ini
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>
=> async is a keyword in python 3.7

cs/__init__.py
=> cli: JSONDecodeError is Python3+

cs/client.py
a smart port from the mypy branch
=> client: avoid using internal members

cs/client.py
- `quote(s, safe="*")` is good enough for the signature check.
- as transform works in-place, it shouldn't return anything.
=> client: smallest safe range when signing

cs/_async.py
introduced by #71 changes to `transform`
=> async: fix regression

cs/client.py, setup.cfg, tests.py, tox.ini
=> lint: add flake8-import-order check

cs/client.py
=> client: fix text/javascript should be ok

cs/client.py
`CloudStackException.__init__()` should respect its parent class signature.
Reported by the mypy experiment.
=> client: respect BaseException interface

cs/client.py
```console
$ cs -t createAffinityGroup name=test type="host anti-affinity-group
GET https://api.exoscale.ch/compute?name=test&type=host+anti-affinity&apiKey=EXO4d60e5e69f0225b35cb4fa05&command=createAffinityGroup&response=json&signatureVersion=3&expires=2019-03-27T08%3A02%3A03%2B0000&signature=x8%2Fl2rYYDlaD%2F2dlPV%2BJdFrCzOc%3D
200 OK
Date: Wed, 27 Mar 2019 07:51:48 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 128
Connection: close
Referrer-Policy: no-referrer-when-downgrade
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding, User-Agent
X-XSS-Protection: 1; mode=block
X-Request-Id: 1d1184a27621aed2e75368a2f5d05ab2 
{ "createaffinitygroupresponse" : …
```
=> client: trace fetch_result

cs/_async.py
* avoid recursion on job polls
* handle #101 change in signing process
=> async: unbreak client

cs/__init__.py
It's not possible to catch this Exception specifically otherwise (e.g. in https://github.com/exoscale/confederatio/pull/579 )
=> Expose CloudStackApiException

setup.cfg, setup.py
this should be feature equivalent and it involves running less Python code.
=> migrate to setup.cfg

.github/workflows/main.yml, README.rst, cs/__init__.py, cs/__main__.py, cs/_async.py, cs/client.py, pyproject.toml, setup.cfg, tests.py, tox.ini
3.7 EOLs in a week, removing it as part of this change.
Also enable github actions.
Fixes #126
=> setup: advertise current python versions
